[package]
name = "rs_lisp"
version = "0.1.0"
authors = ["Colin Davis <ccd.umn.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.21"
strum_macros = "0.21"
rustyline="8.2.0"
